### ISSUE TITLE
Back: Profile picture upload

### ISSUE THREAD

**Issue by M4n0x** [HE-Arc/Zest#42]
Y pas de mécanique sur le backend pour upload une image, pour l'instant on peut mettre un lien dans le modèle du user mais pas d'image a voir si on veut pousser l'image en DB ou si on veut mettre l'image sur le serveur et mettre une référence du lien vers l'image dans le profile utilisateur

**Comment by fridezlucas** [comment]
@M4n0x done :D Nice job
