### ISSUE TITLE
Implement logout with API

### ISSUE THREAD

**Issue by fridezlucas** [HE-Arc/Zest#47]

**Comment by fridezlucas** [comment]
@M4n0x is there any route to revoke the token ?

**Comment by M4n0x** [comment]
![image](https://user-images.githubusercontent.com/6802086/111196276-63866f80-85bd-11eb-87b6-8da6ef29a711.png)
https://stackoverflow.com/questions/52431850/logout-django-rest-framework-jwt

S'il fallait implémenter strictement le logout, une blacklist devrait être implémentée. Dans le cadre de notre projet , on peut se permettre de ne pas implémenter de blacklist qui nécessiterait des implémentations au niveau de la DB ce qui serait contre le principe du stateless de JWT.

Dans notre cadre régler raisonnablement l'expiration des tokens et du refreshtoken devrait amplement suffire
