### ISSUE TITLE
Revue mi-projet

### ISSUE THREAD

**Issue by SpicyPaper** [HE-Arc/Zest#64]
Pourquoi avoir un .gitignore dans votre zestproject ? Vous pourriez ignorez tous vos fichiers plutôt dans le .gitignore principal non ? Je peux comprendre l'intérêt d'avoir 2 .gitignore dans un cas comme le votre ou vous avez le front et le back dans un même dossier. Mais plus ce n'est pas forcément nécessaire à mon sens, à vous de voir.
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/back/zestproject/zestproject/.gitignore#L1-L2

A quoi sert cette migration ?
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/back/zestproject/zestapi/migrations/0008_merge_20210328_1615.py#L1-L14

Quand vous utilisez un code tout fait d'une doc ou autre, ça peut être intéressant de mettre la source. Cela permet à tous les devs de comprendre comment quelque chose fonctionne et de savoir d’où cela provient pour en apprendre plus.
https://www.django-rest-framework.org/api-guide/permissions/#examples
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/back/zestproject/zestapi/permissions.py#L3-L14

Si jamais le DRF met à dispo un champ 'url' que vous pouvez simplement rajouter ici pour avoir l'url complète de la ressource. Ce champ est sympa et permet de naviguer dans la browsable API du DRF plus simplement.
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/back/zestproject/zestapi/serializers.py#L15

Triez vos imports svp. C'est facilement faisable avec un petit clic droit --> sort imports dans vscode. Un formatter sur votre backend pourrait vous aider à faire ça pour vous.
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/back/zestproject/zestapi/urls.py#L1-L9

Vous êtes vraiment sur qu'il n'y à pas moyen de faire plus simple ? Cela me parait contre intuitif à la première lecture. Pour moi le Viewset vous crée toutes les routes pour vous sans que ayez besoin de préciser tous les verbes, etc. Vous pouvez même ajouter des nouvelles routes sans avoir à toutes les préciser comme cela. Petit hint : les routers du DRF :)
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/back/zestproject/zestapi/urls.py#L11-L38

J'aurais mit plus de chose dans votre VueX store. D'ailleurs notez que votre `this.loading = true` est exécutez de manière async également. Si ce n'est pas grave pour vous, alors c'est ok, juste que vous le sachiez. Cool votre ApiRequester.js ;)
https://github.com/HE-Arc/Zest/blob/b8c82448f3b935887c415d29edbee93d8775cba8/front/src/views/SignUp.vue#L96-L120

**Comment by M4n0x** [comment]
Le fichier de migration a été généré automatiquement suite à un merge conflit, j'imagine que c'est une manière pour lui de définir une priorité.

Le fichier git a été changé.

Les routers du DRF ont été ajoutés sauf pour une partie où on a des nested routers c'était plus simple de les laisser en simple path.
