### ISSUE TITLE
Add UI library

### ISSUE THREAD

**Issue by fridezlucas** [HE-Arc/Zest#7]
Choose a UI library to build Zest

**Comment by fridezlucas** [comment]
Choose with an emoji @M4n0x and @BlueSpaceCookie :

- :rocket:  [Vuesax 4 + Vue 2](https://vuesax.com/docs/components/#default)
- :tada:  [Vuetify + Vue 2](https://vuetifyjs.com/en/)

**Comment by M4n0x** [comment]
![image](https://user-images.githubusercontent.com/6802086/109173199-e026ea80-7783-11eb-98ed-064d7c9e3814.png)
(https://www.youtube.com/watch?v=wxBmSAe9xeA)

Le commentaire date un peu mais je pense que ça reste un peu vrai, vuetify offre surement un meilleur support et une meilleure doc

**Comment by fridezlucas** [comment]
So, Vuetify :smile:
